--------------------------------------------------------
--  File created - Tuesday-May-04-2021   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Sequence HISTORIQUE_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "WALID"."HISTORIQUE_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence HISTORIQUE_SEQ1
--------------------------------------------------------

   CREATE SEQUENCE  "WALID"."HISTORIQUE_SEQ1"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 181 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Table CELLULES
--------------------------------------------------------

  CREATE TABLE "WALID"."CELLULES" 
   (	"IDCEL" NUMBER, 
	"NOMBRE_LIT" NUMBER, 
	"NOMBRE_DET" NUMBER, 
	"NOMBRE_DET_MAX" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table CITOYENS
--------------------------------------------------------

  CREATE TABLE "WALID"."CITOYENS" 
   (	"CIN" NUMBER, 
	"NOM" VARCHAR2(20 BYTE), 
	"PRENOM" VARCHAR2(20 BYTE), 
	"ADRESSE" VARCHAR2(20 BYTE), 
	"PHOTO" VARCHAR2(200 BYTE), 
	"DATE_NAISSANCE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table CRIMINELS
--------------------------------------------------------

  CREATE TABLE "WALID"."CRIMINELS" 
   (	"IDC" NUMBER, 
	"NOM" VARCHAR2(20 BYTE), 
	"PRENOM" VARCHAR2(20 BYTE), 
	"ID_DELIT" NUMBER, 
	"IDDET" NUMBER, 
	"AGE" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table DELITS
--------------------------------------------------------

  CREATE TABLE "WALID"."DELITS" 
   (	"ID_DELIT" NUMBER, 
	"DATE_DELIT" DATE, 
	"TYPE" VARCHAR2(20 BYTE), 
	"DESCRIPTION" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table DEMANDES_ADMINISTRATIVES
--------------------------------------------------------

  CREATE TABLE "WALID"."DEMANDES_ADMINISTRATIVES" 
   (	"IDDEM" NUMBER, 
	"NOM" VARCHAR2(20 BYTE), 
	"TYPE" VARCHAR2(20 BYTE), 
	"IDP" NUMBER, 
	"CIN" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table DEMANDE_REPARATION
--------------------------------------------------------

  CREATE TABLE "WALID"."DEMANDE_REPARATION" 
   (	"MATRICULE" NUMBER, 
	"ID_DEMANDE" NUMBER, 
	"TYPE" VARCHAR2(20 BYTE), 
	"DESCRIPTION" VARCHAR2(2000 BYTE), 
	"REPARE" VARCHAR2(4 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table DETENTIONS
--------------------------------------------------------

  CREATE TABLE "WALID"."DETENTIONS" 
   (	"IDDET" NUMBER, 
	"DATE_ENTREE" DATE, 
	"DATE_SORTIE" DATE, 
	"RAISON" VARCHAR2(2000 BYTE), 
	"IDCEL" NUMBER, 
	"IDP" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table EQUIPEMENTS
--------------------------------------------------------

  CREATE TABLE "WALID"."EQUIPEMENTS" 
   (	"IDEQP" NUMBER, 
	"MATRICULE" NUMBER, 
	"TYPE" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table HISTORIQUE
--------------------------------------------------------

  CREATE TABLE "WALID"."HISTORIQUE" 
   (	"ID" NUMBER, 
	"TABLE_M" VARCHAR2(20 BYTE), 
	"TYPE_M" VARCHAR2(20 BYTE), 
	"DATE_M" VARCHAR2(40 BYTE) DEFAULT CURRENT_TIMESTAMP
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table MISSIONS
--------------------------------------------------------

  CREATE TABLE "WALID"."MISSIONS" 
   (	"IDM" NUMBER, 
	"NOM" VARCHAR2(20 BYTE), 
	"TYPE" VARCHAR2(20 BYTE), 
	"DATE_MISSION" DATE, 
	"IDP" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table POLICIER
--------------------------------------------------------

  CREATE TABLE "WALID"."POLICIER" 
   (	"IDP" NUMBER, 
	"NOM" VARCHAR2(20 BYTE), 
	"PRENOM" VARCHAR2(20 BYTE), 
	"GRADE" VARCHAR2(20 BYTE), 
	"IDP_CHEF" NUMBER, 
	"CODE" VARCHAR2(20 BYTE), 
	"ON_JOB" NUMBER DEFAULT 0
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table USER_POLICE
--------------------------------------------------------

  CREATE TABLE "WALID"."USER_POLICE" 
   (	"ID" VARCHAR2(20 BYTE), 
	"USERNAME" VARCHAR2(50 BYTE), 
	"PASSWORD" VARCHAR2(20 BYTE), 
	"IDP" VARCHAR2(20 BYTE), 
	"RANK" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table VEHICULES
--------------------------------------------------------

  CREATE TABLE "WALID"."VEHICULES" 
   (	"NOM_MARQUE" VARCHAR2(20 BYTE), 
	"MATRICULE" NUMBER, 
	"DATE_ACHAT" DATE, 
	"IDP" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into WALID.CELLULES
SET DEFINE OFF;
Insert into WALID.CELLULES (IDCEL,NOMBRE_LIT,NOMBRE_DET,NOMBRE_DET_MAX) values (12,15,19,20);
Insert into WALID.CELLULES (IDCEL,NOMBRE_LIT,NOMBRE_DET,NOMBRE_DET_MAX) values (1,30,40,10);
REM INSERTING into WALID.CITOYENS
SET DEFINE OFF;
Insert into WALID.CITOYENS (CIN,NOM,PRENOM,ADRESSE,PHOTO,DATE_NAISSANCE) values (1515,'walid','jaouani','kkk','wawaw',to_date('29-APR-21','DD-MON-RR'));
REM INSERTING into WALID.CRIMINELS
SET DEFINE OFF;
REM INSERTING into WALID.DELITS
SET DEFINE OFF;
Insert into WALID.DELITS (ID_DELIT,DATE_DELIT,TYPE,DESCRIPTION) values (1,to_date('26-APR-21','DD-MON-RR'),'aaa','aaaaa');
REM INSERTING into WALID.DEMANDES_ADMINISTRATIVES
SET DEFINE OFF;
REM INSERTING into WALID.DEMANDE_REPARATION
SET DEFINE OFF;
REM INSERTING into WALID.DETENTIONS
SET DEFINE OFF;
REM INSERTING into WALID.EQUIPEMENTS
SET DEFINE OFF;
REM INSERTING into WALID.HISTORIQUE
SET DEFINE OFF;
Insert into WALID.HISTORIQUE (ID,TABLE_M,TYPE_M,DATE_M) values (4,'equipements','A','29-APR-21 18.07.10.481000 +01:00');
Insert into WALID.HISTORIQUE (ID,TABLE_M,TYPE_M,DATE_M) values (2,'cellule','A','29-APR-21 15.00.04.015000 AFRICA/LUANDA');
Insert into WALID.HISTORIQUE (ID,TABLE_M,TYPE_M,DATE_M) values (3,'vehicules','A','29-APR-21 17.57.51.898000 AFRICA/LUANDA');
Insert into WALID.HISTORIQUE (ID,TABLE_M,TYPE_M,DATE_M) values (5,'citoyens','A','29-APR-21 18.09.51.886000 AFRICA/LUANDA');
Insert into WALID.HISTORIQUE (ID,TABLE_M,TYPE_M,DATE_M) values (6,'demandes rep','D','29-APR-21 18.10.48.115000 +01:00');
Insert into WALID.HISTORIQUE (ID,TABLE_M,TYPE_M,DATE_M) values (7,'equipements','D','29-APR-21 18.10.48.116000 +01:00');
Insert into WALID.HISTORIQUE (ID,TABLE_M,TYPE_M,DATE_M) values (8,'vehicules','D','29-APR-21 18.10.48.116000 +01:00');
Insert into WALID.HISTORIQUE (ID,TABLE_M,TYPE_M,DATE_M) values (9,'criminels','D','29-APR-21 18.20.25.455000 AFRICA/LUANDA');
Insert into WALID.HISTORIQUE (ID,TABLE_M,TYPE_M,DATE_M) values (10,'demandes rep','D','29-APR-21 18.20.25.455000 AFRICA/LUANDA');
Insert into WALID.HISTORIQUE (ID,TABLE_M,TYPE_M,DATE_M) values (11,'equipements','D','29-APR-21 18.20.25.455000 AFRICA/LUANDA');
Insert into WALID.HISTORIQUE (ID,TABLE_M,TYPE_M,DATE_M) values (12,'demandes admin','D','29-APR-21 18.20.25.455000 AFRICA/LUANDA');
Insert into WALID.HISTORIQUE (ID,TABLE_M,TYPE_M,DATE_M) values (13,'detentions','D','29-APR-21 18.20.25.455000 AFRICA/LUANDA');
Insert into WALID.HISTORIQUE (ID,TABLE_M,TYPE_M,DATE_M) values (14,'missions','D','29-APR-21 18.20.25.456000 AFRICA/LUANDA');
Insert into WALID.HISTORIQUE (ID,TABLE_M,TYPE_M,DATE_M) values (15,'vehicules','D','29-APR-21 18.20.25.456000 AFRICA/LUANDA');
Insert into WALID.HISTORIQUE (ID,TABLE_M,TYPE_M,DATE_M) values (16,'policiers','D','29-APR-21 18.20.25.456000 AFRICA/LUANDA');
Insert into WALID.HISTORIQUE (ID,TABLE_M,TYPE_M,DATE_M) values (17,'POLICIER','A','29-APR-21 18.23.33.295000 AFRICA/LUANDA');
Insert into WALID.HISTORIQUE (ID,TABLE_M,TYPE_M,DATE_M) values (18,'criminels','D','29-APR-21 18.23.39.270000 AFRICA/LUANDA');
Insert into WALID.HISTORIQUE (ID,TABLE_M,TYPE_M,DATE_M) values (19,'demandes rep','D','29-APR-21 18.23.39.270000 AFRICA/LUANDA');
Insert into WALID.HISTORIQUE (ID,TABLE_M,TYPE_M,DATE_M) values (20,'equipements','D','29-APR-21 18.23.39.270000 AFRICA/LUANDA');
Insert into WALID.HISTORIQUE (ID,TABLE_M,TYPE_M,DATE_M) values (21,'demandes admin','D','29-APR-21 18.23.39.270000 AFRICA/LUANDA');
Insert into WALID.HISTORIQUE (ID,TABLE_M,TYPE_M,DATE_M) values (22,'detentions','D','29-APR-21 18.23.39.270000 AFRICA/LUANDA');
Insert into WALID.HISTORIQUE (ID,TABLE_M,TYPE_M,DATE_M) values (23,'missions','D','29-APR-21 18.23.39.270000 AFRICA/LUANDA');
Insert into WALID.HISTORIQUE (ID,TABLE_M,TYPE_M,DATE_M) values (24,'vehicules','D','29-APR-21 18.23.39.271000 AFRICA/LUANDA');
Insert into WALID.HISTORIQUE (ID,TABLE_M,TYPE_M,DATE_M) values (25,'policiers','D','29-APR-21 18.23.39.271000 AFRICA/LUANDA');
Insert into WALID.HISTORIQUE (ID,TABLE_M,TYPE_M,DATE_M) values (26,'demandes rep','D','29-APR-21 18.26.31.623000 AFRICA/LUANDA');
Insert into WALID.HISTORIQUE (ID,TABLE_M,TYPE_M,DATE_M) values (27,'equipements','D','29-APR-21 18.26.31.623000 AFRICA/LUANDA');
Insert into WALID.HISTORIQUE (ID,TABLE_M,TYPE_M,DATE_M) values (28,'vehicules','D','29-APR-21 18.26.31.623000 AFRICA/LUANDA');
Insert into WALID.HISTORIQUE (ID,TABLE_M,TYPE_M,DATE_M) values (29,'equipements','D','29-APR-21 18.28.48.477000 +01:00');
Insert into WALID.HISTORIQUE (ID,TABLE_M,TYPE_M,DATE_M) values (30,'vehicules','U','29-APR-21 18.39.39.685000 +01:00');
Insert into WALID.HISTORIQUE (ID,TABLE_M,TYPE_M,DATE_M) values (31,'vehicules','U','29-APR-21 18.40.20.854000 +01:00');
Insert into WALID.HISTORIQUE (ID,TABLE_M,TYPE_M,DATE_M) values (32,'POLICIER','A','29-APR-21 19.06.06.168000 +01:00');
Insert into WALID.HISTORIQUE (ID,TABLE_M,TYPE_M,DATE_M) values (33,'criminels','D','29-APR-21 19.08.34.832000 +01:00');
Insert into WALID.HISTORIQUE (ID,TABLE_M,TYPE_M,DATE_M) values (34,'demandes rep','D','29-APR-21 19.08.34.833000 +01:00');
Insert into WALID.HISTORIQUE (ID,TABLE_M,TYPE_M,DATE_M) values (35,'equipements','D','29-APR-21 19.08.34.833000 +01:00');
Insert into WALID.HISTORIQUE (ID,TABLE_M,TYPE_M,DATE_M) values (36,'demandes admin','D','29-APR-21 19.08.34.833000 +01:00');
Insert into WALID.HISTORIQUE (ID,TABLE_M,TYPE_M,DATE_M) values (37,'detentions','D','29-APR-21 19.08.34.833000 +01:00');
Insert into WALID.HISTORIQUE (ID,TABLE_M,TYPE_M,DATE_M) values (38,'missions','D','29-APR-21 19.08.34.833000 +01:00');
Insert into WALID.HISTORIQUE (ID,TABLE_M,TYPE_M,DATE_M) values (39,'vehicules','D','29-APR-21 19.08.34.833000 +01:00');
Insert into WALID.HISTORIQUE (ID,TABLE_M,TYPE_M,DATE_M) values (40,'policiers','D','29-APR-21 19.08.34.833000 +01:00');
Insert into WALID.HISTORIQUE (ID,TABLE_M,TYPE_M,DATE_M) values (41,'demandes rep','D','29-APR-21 19.17.41.378000 AFRICA/LUANDA');
Insert into WALID.HISTORIQUE (ID,TABLE_M,TYPE_M,DATE_M) values (42,'demandes rep','D','29-APR-21 19.18.20.904000 +01:00');
Insert into WALID.HISTORIQUE (ID,TABLE_M,TYPE_M,DATE_M) values (43,'demandes rep','D','29-APR-21 19.19.12.424000 +01:00');
Insert into WALID.HISTORIQUE (ID,TABLE_M,TYPE_M,DATE_M) values (44,'equipements','D','29-APR-21 19.19.12.424000 +01:00');
Insert into WALID.HISTORIQUE (ID,TABLE_M,TYPE_M,DATE_M) values (45,'vehicules','D','29-APR-21 19.19.12.424000 +01:00');
Insert into WALID.HISTORIQUE (ID,TABLE_M,TYPE_M,DATE_M) values (46,'vehicules','A','29-APR-21 21.02.01.479000 +01:00');
Insert into WALID.HISTORIQUE (ID,TABLE_M,TYPE_M,DATE_M) values (47,'vehicules','A','29-APR-21 21.03.13.540000 +01:00');
Insert into WALID.HISTORIQUE (ID,TABLE_M,TYPE_M,DATE_M) values (61,'policiers','U','01-MAY-21 15.46.19.827000 +01:00');
Insert into WALID.HISTORIQUE (ID,TABLE_M,TYPE_M,DATE_M) values (62,'policiers','U','02-MAY-21 14.53.53.481000 +01:00');
Insert into WALID.HISTORIQUE (ID,TABLE_M,TYPE_M,DATE_M) values (63,'policiers','U','02-MAY-21 15.23.54.969000 +01:00');
Insert into WALID.HISTORIQUE (ID,TABLE_M,TYPE_M,DATE_M) values (64,'policiers','U','02-MAY-21 15.25.37.402000 +01:00');
Insert into WALID.HISTORIQUE (ID,TABLE_M,TYPE_M,DATE_M) values (65,'cellule','U','02-MAY-21 15.26.01.181000 +01:00');
Insert into WALID.HISTORIQUE (ID,TABLE_M,TYPE_M,DATE_M) values (66,'cellule','U','02-MAY-21 15.26.20.154000 +01:00');
Insert into WALID.HISTORIQUE (ID,TABLE_M,TYPE_M,DATE_M) values (67,'policiers','U','02-MAY-21 15.28.51.383000 +01:00');
Insert into WALID.HISTORIQUE (ID,TABLE_M,TYPE_M,DATE_M) values (68,'policiers','U','02-MAY-21 15.28.54.726000 +01:00');
Insert into WALID.HISTORIQUE (ID,TABLE_M,TYPE_M,DATE_M) values (69,'policiers','U','02-MAY-21 15.29.01.701000 +01:00');
Insert into WALID.HISTORIQUE (ID,TABLE_M,TYPE_M,DATE_M) values (70,'policiers','U','02-MAY-21 15.29.09.354000 +01:00');
Insert into WALID.HISTORIQUE (ID,TABLE_M,TYPE_M,DATE_M) values (71,'cellule','U','02-MAY-21 15.34.20.023000 +01:00');
Insert into WALID.HISTORIQUE (ID,TABLE_M,TYPE_M,DATE_M) values (72,'cellule','U','02-MAY-21 15.35.04.641000 +01:00');
Insert into WALID.HISTORIQUE (ID,TABLE_M,TYPE_M,DATE_M) values (73,'cellule','U','02-MAY-21 15.36.53.203000 +01:00');
Insert into WALID.HISTORIQUE (ID,TABLE_M,TYPE_M,DATE_M) values (74,'policiers','U','02-MAY-21 16.09.13.185000 +01:00');
Insert into WALID.HISTORIQUE (ID,TABLE_M,TYPE_M,DATE_M) values (75,'policiers','U','02-MAY-21 16.09.19.772000 +01:00');
Insert into WALID.HISTORIQUE (ID,TABLE_M,TYPE_M,DATE_M) values (76,'demandes rep','D','03-MAY-21 16.53.45.482000 +01:00');
Insert into WALID.HISTORIQUE (ID,TABLE_M,TYPE_M,DATE_M) values (77,'equipements','D','03-MAY-21 16.53.45.483000 +01:00');
Insert into WALID.HISTORIQUE (ID,TABLE_M,TYPE_M,DATE_M) values (78,'vehicules','D','03-MAY-21 16.53.45.483000 +01:00');
Insert into WALID.HISTORIQUE (ID,TABLE_M,TYPE_M,DATE_M) values (79,'policiers','U','04-MAY-21 16.59.28.984000 +01:00');
Insert into WALID.HISTORIQUE (ID,TABLE_M,TYPE_M,DATE_M) values (80,'policiers','U','04-MAY-21 16.59.29.975000 +01:00');
Insert into WALID.HISTORIQUE (ID,TABLE_M,TYPE_M,DATE_M) values (81,'policiers','U','04-MAY-21 16.59.30.973000 +01:00');
Insert into WALID.HISTORIQUE (ID,TABLE_M,TYPE_M,DATE_M) values (82,'policiers','U','04-MAY-21 16.59.31.978000 +01:00');
Insert into WALID.HISTORIQUE (ID,TABLE_M,TYPE_M,DATE_M) values (83,'policiers','U','04-MAY-21 16.59.32.977000 +01:00');
Insert into WALID.HISTORIQUE (ID,TABLE_M,TYPE_M,DATE_M) values (84,'policiers','U','04-MAY-21 16.59.33.976000 +01:00');
Insert into WALID.HISTORIQUE (ID,TABLE_M,TYPE_M,DATE_M) values (85,'policiers','U','04-MAY-21 16.59.34.980000 +01:00');
Insert into WALID.HISTORIQUE (ID,TABLE_M,TYPE_M,DATE_M) values (86,'policiers','U','04-MAY-21 16.59.35.979000 +01:00');
Insert into WALID.HISTORIQUE (ID,TABLE_M,TYPE_M,DATE_M) values (87,'policiers','U','04-MAY-21 16.59.36.979000 +01:00');
Insert into WALID.HISTORIQUE (ID,TABLE_M,TYPE_M,DATE_M) values (88,'policiers','U','04-MAY-21 16.59.37.981000 +01:00');
Insert into WALID.HISTORIQUE (ID,TABLE_M,TYPE_M,DATE_M) values (89,'policiers','U','04-MAY-21 16.59.38.981000 +01:00');
Insert into WALID.HISTORIQUE (ID,TABLE_M,TYPE_M,DATE_M) values (90,'policiers','U','04-MAY-21 16.59.39.985000 +01:00');
Insert into WALID.HISTORIQUE (ID,TABLE_M,TYPE_M,DATE_M) values (91,'policiers','U','04-MAY-21 16.59.40.984000 +01:00');
Insert into WALID.HISTORIQUE (ID,TABLE_M,TYPE_M,DATE_M) values (92,'policiers','U','04-MAY-21 16.59.41.984000 +01:00');
Insert into WALID.HISTORIQUE (ID,TABLE_M,TYPE_M,DATE_M) values (93,'policiers','U','04-MAY-21 16.59.42.997000 +01:00');
Insert into WALID.HISTORIQUE (ID,TABLE_M,TYPE_M,DATE_M) values (94,'policiers','U','04-MAY-21 16.59.43.986000 +01:00');
Insert into WALID.HISTORIQUE (ID,TABLE_M,TYPE_M,DATE_M) values (95,'policiers','U','04-MAY-21 16.59.44.985000 +01:00');
Insert into WALID.HISTORIQUE (ID,TABLE_M,TYPE_M,DATE_M) values (96,'policiers','U','04-MAY-21 16.59.45.989000 +01:00');
Insert into WALID.HISTORIQUE (ID,TABLE_M,TYPE_M,DATE_M) values (97,'policiers','U','04-MAY-21 16.59.47.000000 +01:00');
Insert into WALID.HISTORIQUE (ID,TABLE_M,TYPE_M,DATE_M) values (98,'policiers','U','04-MAY-21 16.59.47.992000 +01:00');
Insert into WALID.HISTORIQUE (ID,TABLE_M,TYPE_M,DATE_M) values (99,'policiers','U','04-MAY-21 16.59.48.995000 +01:00');
Insert into WALID.HISTORIQUE (ID,TABLE_M,TYPE_M,DATE_M) values (100,'policiers','U','04-MAY-21 16.59.49.994000 +01:00');
Insert into WALID.HISTORIQUE (ID,TABLE_M,TYPE_M,DATE_M) values (101,'policiers','U','04-MAY-21 16.59.50.995000 +01:00');
Insert into WALID.HISTORIQUE (ID,TABLE_M,TYPE_M,DATE_M) values (102,'policiers','U','04-MAY-21 16.59.51.993000 +01:00');
Insert into WALID.HISTORIQUE (ID,TABLE_M,TYPE_M,DATE_M) values (103,'policiers','U','04-MAY-21 16.59.52.996000 +01:00');
Insert into WALID.HISTORIQUE (ID,TABLE_M,TYPE_M,DATE_M) values (104,'policiers','U','04-MAY-21 16.59.53.998000 +01:00');
Insert into WALID.HISTORIQUE (ID,TABLE_M,TYPE_M,DATE_M) values (105,'policiers','U','04-MAY-21 16.59.54.999000 +01:00');
Insert into WALID.HISTORIQUE (ID,TABLE_M,TYPE_M,DATE_M) values (106,'policiers','U','04-MAY-21 16.59.56.001000 +01:00');
Insert into WALID.HISTORIQUE (ID,TABLE_M,TYPE_M,DATE_M) values (107,'policiers','U','04-MAY-21 16.59.57.002000 +01:00');
Insert into WALID.HISTORIQUE (ID,TABLE_M,TYPE_M,DATE_M) values (108,'policiers','U','04-MAY-21 16.59.58.001000 +01:00');
Insert into WALID.HISTORIQUE (ID,TABLE_M,TYPE_M,DATE_M) values (109,'policiers','U','04-MAY-21 16.59.59.005000 +01:00');
Insert into WALID.HISTORIQUE (ID,TABLE_M,TYPE_M,DATE_M) values (110,'policiers','U','04-MAY-21 17.00.00.001000 +01:00');
Insert into WALID.HISTORIQUE (ID,TABLE_M,TYPE_M,DATE_M) values (111,'policiers','U','04-MAY-21 17.00.01.000000 +01:00');
Insert into WALID.HISTORIQUE (ID,TABLE_M,TYPE_M,DATE_M) values (112,'policiers','U','04-MAY-21 17.00.02.004000 +01:00');
Insert into WALID.HISTORIQUE (ID,TABLE_M,TYPE_M,DATE_M) values (113,'policiers','U','04-MAY-21 17.00.03.007000 +01:00');
Insert into WALID.HISTORIQUE (ID,TABLE_M,TYPE_M,DATE_M) values (114,'policiers','U','04-MAY-21 17.00.04.007000 +01:00');
Insert into WALID.HISTORIQUE (ID,TABLE_M,TYPE_M,DATE_M) values (115,'policiers','U','04-MAY-21 17.00.05.008000 +01:00');
Insert into WALID.HISTORIQUE (ID,TABLE_M,TYPE_M,DATE_M) values (116,'policiers','U','04-MAY-21 17.00.06.008000 +01:00');
Insert into WALID.HISTORIQUE (ID,TABLE_M,TYPE_M,DATE_M) values (117,'policiers','U','04-MAY-21 17.00.07.012000 +01:00');
Insert into WALID.HISTORIQUE (ID,TABLE_M,TYPE_M,DATE_M) values (118,'policiers','U','04-MAY-21 17.00.08.008000 +01:00');
Insert into WALID.HISTORIQUE (ID,TABLE_M,TYPE_M,DATE_M) values (119,'policiers','U','04-MAY-21 17.00.09.008000 +01:00');
Insert into WALID.HISTORIQUE (ID,TABLE_M,TYPE_M,DATE_M) values (120,'policiers','U','04-MAY-21 17.00.10.012000 +01:00');
Insert into WALID.HISTORIQUE (ID,TABLE_M,TYPE_M,DATE_M) values (121,'policiers','U','04-MAY-21 17.00.11.012000 +01:00');
Insert into WALID.HISTORIQUE (ID,TABLE_M,TYPE_M,DATE_M) values (122,'policiers','U','04-MAY-21 17.00.12.011000 +01:00');
Insert into WALID.HISTORIQUE (ID,TABLE_M,TYPE_M,DATE_M) values (123,'policiers','U','04-MAY-21 17.00.13.017000 +01:00');
Insert into WALID.HISTORIQUE (ID,TABLE_M,TYPE_M,DATE_M) values (124,'policiers','U','04-MAY-21 17.00.14.013000 +01:00');
Insert into WALID.HISTORIQUE (ID,TABLE_M,TYPE_M,DATE_M) values (125,'policiers','U','04-MAY-21 17.00.15.017000 +01:00');
Insert into WALID.HISTORIQUE (ID,TABLE_M,TYPE_M,DATE_M) values (126,'policiers','U','04-MAY-21 17.00.16.019000 +01:00');
Insert into WALID.HISTORIQUE (ID,TABLE_M,TYPE_M,DATE_M) values (127,'policiers','U','04-MAY-21 17.00.17.017000 +01:00');
Insert into WALID.HISTORIQUE (ID,TABLE_M,TYPE_M,DATE_M) values (128,'policiers','U','04-MAY-21 17.00.18.022000 +01:00');
Insert into WALID.HISTORIQUE (ID,TABLE_M,TYPE_M,DATE_M) values (129,'policiers','U','04-MAY-21 17.00.19.019000 +01:00');
Insert into WALID.HISTORIQUE (ID,TABLE_M,TYPE_M,DATE_M) values (130,'policiers','U','04-MAY-21 17.00.20.019000 +01:00');
Insert into WALID.HISTORIQUE (ID,TABLE_M,TYPE_M,DATE_M) values (131,'policiers','U','04-MAY-21 17.00.21.025000 +01:00');
Insert into WALID.HISTORIQUE (ID,TABLE_M,TYPE_M,DATE_M) values (132,'policiers','U','04-MAY-21 17.00.22.021000 +01:00');
Insert into WALID.HISTORIQUE (ID,TABLE_M,TYPE_M,DATE_M) values (133,'policiers','U','04-MAY-21 17.00.23.025000 +01:00');
Insert into WALID.HISTORIQUE (ID,TABLE_M,TYPE_M,DATE_M) values (134,'policiers','U','04-MAY-21 17.00.24.024000 +01:00');
Insert into WALID.HISTORIQUE (ID,TABLE_M,TYPE_M,DATE_M) values (135,'policiers','U','04-MAY-21 17.00.25.022000 +01:00');
Insert into WALID.HISTORIQUE (ID,TABLE_M,TYPE_M,DATE_M) values (136,'policiers','U','04-MAY-21 17.00.26.026000 +01:00');
Insert into WALID.HISTORIQUE (ID,TABLE_M,TYPE_M,DATE_M) values (137,'policiers','U','04-MAY-21 17.00.27.025000 +01:00');
Insert into WALID.HISTORIQUE (ID,TABLE_M,TYPE_M,DATE_M) values (138,'policiers','U','04-MAY-21 17.00.28.028000 +01:00');
Insert into WALID.HISTORIQUE (ID,TABLE_M,TYPE_M,DATE_M) values (139,'policiers','U','04-MAY-21 17.00.29.031000 +01:00');
Insert into WALID.HISTORIQUE (ID,TABLE_M,TYPE_M,DATE_M) values (140,'policiers','U','04-MAY-21 17.00.30.028000 +01:00');
Insert into WALID.HISTORIQUE (ID,TABLE_M,TYPE_M,DATE_M) values (141,'policiers','U','04-MAY-21 17.00.31.034000 +01:00');
Insert into WALID.HISTORIQUE (ID,TABLE_M,TYPE_M,DATE_M) values (142,'policiers','U','04-MAY-21 17.00.32.030000 +01:00');
Insert into WALID.HISTORIQUE (ID,TABLE_M,TYPE_M,DATE_M) values (143,'policiers','U','04-MAY-21 17.00.33.034000 +01:00');
Insert into WALID.HISTORIQUE (ID,TABLE_M,TYPE_M,DATE_M) values (144,'policiers','U','04-MAY-21 17.00.34.037000 +01:00');
Insert into WALID.HISTORIQUE (ID,TABLE_M,TYPE_M,DATE_M) values (145,'policiers','U','04-MAY-21 17.00.35.033000 +01:00');
Insert into WALID.HISTORIQUE (ID,TABLE_M,TYPE_M,DATE_M) values (146,'policiers','U','04-MAY-21 17.00.36.035000 +01:00');
Insert into WALID.HISTORIQUE (ID,TABLE_M,TYPE_M,DATE_M) values (147,'policiers','U','04-MAY-21 17.00.37.036000 +01:00');
Insert into WALID.HISTORIQUE (ID,TABLE_M,TYPE_M,DATE_M) values (148,'policiers','U','04-MAY-21 17.00.38.038000 +01:00');
Insert into WALID.HISTORIQUE (ID,TABLE_M,TYPE_M,DATE_M) values (149,'policiers','U','04-MAY-21 17.00.39.045000 +01:00');
Insert into WALID.HISTORIQUE (ID,TABLE_M,TYPE_M,DATE_M) values (150,'policiers','U','04-MAY-21 17.00.40.041000 +01:00');
Insert into WALID.HISTORIQUE (ID,TABLE_M,TYPE_M,DATE_M) values (151,'policiers','U','04-MAY-21 17.00.41.041000 +01:00');
Insert into WALID.HISTORIQUE (ID,TABLE_M,TYPE_M,DATE_M) values (152,'policiers','U','04-MAY-21 17.00.42.045000 +01:00');
Insert into WALID.HISTORIQUE (ID,TABLE_M,TYPE_M,DATE_M) values (153,'policiers','U','04-MAY-21 17.00.43.040000 +01:00');
Insert into WALID.HISTORIQUE (ID,TABLE_M,TYPE_M,DATE_M) values (154,'policiers','U','04-MAY-21 17.00.44.040000 +01:00');
Insert into WALID.HISTORIQUE (ID,TABLE_M,TYPE_M,DATE_M) values (155,'cellule','U','04-MAY-21 17.00.45.057000 +01:00');
Insert into WALID.HISTORIQUE (ID,TABLE_M,TYPE_M,DATE_M) values (156,'policiers','U','04-MAY-21 22.16.50.690000 +01:00');
Insert into WALID.HISTORIQUE (ID,TABLE_M,TYPE_M,DATE_M) values (157,'policiers','U','04-MAY-21 22.16.55.514000 +01:00');
Insert into WALID.HISTORIQUE (ID,TABLE_M,TYPE_M,DATE_M) values (158,'policiers','U','04-MAY-21 22.17.03.001000 +01:00');
Insert into WALID.HISTORIQUE (ID,TABLE_M,TYPE_M,DATE_M) values (159,'policiers','U','04-MAY-21 22.17.13.991000 +01:00');
Insert into WALID.HISTORIQUE (ID,TABLE_M,TYPE_M,DATE_M) values (160,'policiers','U','04-MAY-21 22.17.18.827000 +01:00');
Insert into WALID.HISTORIQUE (ID,TABLE_M,TYPE_M,DATE_M) values (161,'policiers','U','04-MAY-21 22.17.22.191000 +01:00');
Insert into WALID.HISTORIQUE (ID,TABLE_M,TYPE_M,DATE_M) values (162,'policiers','U','04-MAY-21 22.17.28.186000 +01:00');
Insert into WALID.HISTORIQUE (ID,TABLE_M,TYPE_M,DATE_M) values (163,'cellule','U','04-MAY-21 22.17.47.629000 +01:00');
Insert into WALID.HISTORIQUE (ID,TABLE_M,TYPE_M,DATE_M) values (164,'cellule','U','04-MAY-21 22.21.08.454000 +01:00');
Insert into WALID.HISTORIQUE (ID,TABLE_M,TYPE_M,DATE_M) values (165,'cellule','U','04-MAY-21 22.23.52.532000 +01:00');
Insert into WALID.HISTORIQUE (ID,TABLE_M,TYPE_M,DATE_M) values (166,'cellule','U','04-MAY-21 22.25.51.473000 +01:00');
Insert into WALID.HISTORIQUE (ID,TABLE_M,TYPE_M,DATE_M) values (167,'policiers','U','04-MAY-21 22.26.19.938000 +01:00');
Insert into WALID.HISTORIQUE (ID,TABLE_M,TYPE_M,DATE_M) values (168,'policiers','U','04-MAY-21 22.26.36.560000 +01:00');
Insert into WALID.HISTORIQUE (ID,TABLE_M,TYPE_M,DATE_M) values (169,'policiers','U','04-MAY-21 22.29.53.496000 +01:00');
Insert into WALID.HISTORIQUE (ID,TABLE_M,TYPE_M,DATE_M) values (170,'policiers','U','04-MAY-21 22.30.01.499000 +01:00');
REM INSERTING into WALID.MISSIONS
SET DEFINE OFF;
REM INSERTING into WALID.POLICIER
SET DEFINE OFF;
Insert into WALID.POLICIER (IDP,NOM,PRENOM,GRADE,IDP_CHEF,CODE,ON_JOB) values (1,'samir','lowsif','gamer',1,'B7 36 FD A7',1);
REM INSERTING into WALID.USER_POLICE
SET DEFINE OFF;
Insert into WALID.USER_POLICE (ID,USERNAME,PASSWORD,IDP,RANK) values ('1','walid','walid','1','retard');
REM INSERTING into WALID.VEHICULES
SET DEFINE OFF;
Insert into WALID.VEHICULES (NOM_MARQUE,MATRICULE,DATE_ACHAT,IDP) values ('zeazeazuyjyui',5554,to_date('01-JAN-00','DD-MON-RR'),1);
Insert into WALID.VEHICULES (NOM_MARQUE,MATRICULE,DATE_ACHAT,IDP) values ('zeazeaz',555,to_date('01-JAN-00','DD-MON-RR'),1);
--------------------------------------------------------
--  DDL for Index CRIMINELS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "WALID"."CRIMINELS_PK" ON "WALID"."CRIMINELS" ("IDC") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index DEMANDE_REPARATION_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "WALID"."DEMANDE_REPARATION_PK" ON "WALID"."DEMANDE_REPARATION" ("ID_DEMANDE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index USER_POLICE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "WALID"."USER_POLICE_PK" ON "WALID"."USER_POLICE" ("ID", "USERNAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index MISSIONS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "WALID"."MISSIONS_PK" ON "WALID"."MISSIONS" ("IDM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index DELITS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "WALID"."DELITS_PK" ON "WALID"."DELITS" ("ID_DELIT") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index DETENTIONS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "WALID"."DETENTIONS_PK" ON "WALID"."DETENTIONS" ("IDDET") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index CELLULES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "WALID"."CELLULES_PK" ON "WALID"."CELLULES" ("IDCEL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index DEMANDES_ADMINISTRATIVES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "WALID"."DEMANDES_ADMINISTRATIVES_PK" ON "WALID"."DEMANDES_ADMINISTRATIVES" ("IDDEM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index VEHICULES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "WALID"."VEHICULES_PK" ON "WALID"."VEHICULES" ("MATRICULE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index POLICIER_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "WALID"."POLICIER_PK" ON "WALID"."POLICIER" ("IDP") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index HISTORIQUE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "WALID"."HISTORIQUE_PK" ON "WALID"."HISTORIQUE" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index CITOYENS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "WALID"."CITOYENS_PK" ON "WALID"."CITOYENS" ("CIN") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index EQUIPEMENTS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "WALID"."EQUIPEMENTS_PK" ON "WALID"."EQUIPEMENTS" ("IDEQP") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Trigger HISTORIQUE_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "WALID"."HISTORIQUE_TRG" 
BEFORE INSERT ON HISTORIQUE 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    NULL;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "WALID"."HISTORIQUE_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger HISTORIQUE_TRG1
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "WALID"."HISTORIQUE_TRG1" 
BEFORE INSERT ON HISTORIQUE 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID IS NULL THEN
      SELECT HISTORIQUE_SEQ1.NEXTVAL INTO :NEW.ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "WALID"."HISTORIQUE_TRG1" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRIGGER1
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "WALID"."TRIGGER1" 
AFTER INSERT ON DEMANDE_REPARATION 
BEGIN
INSERT INTO HISTORIQUE(table_m,type_m) VALUES ('demandes rep','A');
  NULL;
END;
/
ALTER TRIGGER "WALID"."TRIGGER1" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRIGGER_CELLULES_DELETE
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "WALID"."TRIGGER_CELLULES_DELETE" 
AFTER DELETE ON CELLULES 
BEGIN
INSERT INTO HISTORIQUE(table_m,type_m) VALUES ('cellule','D');
  NULL;
END;
/
ALTER TRIGGER "WALID"."TRIGGER_CELLULES_DELETE" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRIGGER_CELLULES_UPDATE
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "WALID"."TRIGGER_CELLULES_UPDATE" 
AFTER UPDATE ON CELLULES 
BEGIN
INSERT INTO HISTORIQUE(table_m,type_m) VALUES ('cellule','U');
  NULL;
END;
/
ALTER TRIGGER "WALID"."TRIGGER_CELLULES_UPDATE" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRIGGER_CELLULE_AJOUT
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "WALID"."TRIGGER_CELLULE_AJOUT" 
AFTER INSERT ON CELLULES 
BEGIN
    NULL;
    INSERT INTO HISTORIQUE(table_m,type_m) VALUES ('cellule','A');

END;
/
ALTER TRIGGER "WALID"."TRIGGER_CELLULE_AJOUT" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRIGGER_CITOYENS_AJOUT
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "WALID"."TRIGGER_CITOYENS_AJOUT" 
AFTER INSERT ON CITOYENS 
BEGIN
    INSERT INTO HISTORIQUE(table_m,type_m) VALUES ('citoyens','A');
  NULL;
END;
/
ALTER TRIGGER "WALID"."TRIGGER_CITOYENS_AJOUT" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRIGGER_CITOYENS_DELETE
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "WALID"."TRIGGER_CITOYENS_DELETE" 
AFTER DELETE ON CITOYENS 
BEGIN
INSERT INTO HISTORIQUE(table_m,type_m) VALUES ('citoyens','D');
  NULL;
END;
/
ALTER TRIGGER "WALID"."TRIGGER_CITOYENS_DELETE" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRIGGER_CITOYENS_UPDATE
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "WALID"."TRIGGER_CITOYENS_UPDATE" 
AFTER UPDATE ON CITOYENS 
BEGIN
INSERT INTO HISTORIQUE(table_m,type_m) VALUES ('citoyens','U');
  NULL;
END;
/
ALTER TRIGGER "WALID"."TRIGGER_CITOYENS_UPDATE" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRIGGER_CRIMINELS_AJOUT
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "WALID"."TRIGGER_CRIMINELS_AJOUT" 
AFTER INSERT ON CRIMINELS 
BEGIN
    INSERT INTO HISTORIQUE(table_m,type_m) VALUES ('criminels','A');
  NULL;
END;
/
ALTER TRIGGER "WALID"."TRIGGER_CRIMINELS_AJOUT" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRIGGER_CRIMINELS_DELETE
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "WALID"."TRIGGER_CRIMINELS_DELETE" 
AFTER DELETE ON CRIMINELS 
BEGIN
INSERT INTO HISTORIQUE(table_m,type_m) VALUES ('criminels','D');
  NULL;
END;
/
ALTER TRIGGER "WALID"."TRIGGER_CRIMINELS_DELETE" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRIGGER_CRIMINELS_UPDATE
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "WALID"."TRIGGER_CRIMINELS_UPDATE" 
AFTER UPDATE ON CRIMINELS 
BEGIN
INSERT INTO HISTORIQUE(table_m,type_m) VALUES ('criminels','U');
  NULL;
END;
/
ALTER TRIGGER "WALID"."TRIGGER_CRIMINELS_UPDATE" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRIGGER_DELITS_AJOUT
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "WALID"."TRIGGER_DELITS_AJOUT" 
AFTER INSERT ON DELITS 
BEGIN
    INSERT INTO HISTORIQUE(table_m,type_m) VALUES ('delits','A');
  NULL;
END;
/
ALTER TRIGGER "WALID"."TRIGGER_DELITS_AJOUT" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRIGGER_DELITS_DELETE
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "WALID"."TRIGGER_DELITS_DELETE" 
AFTER DELETE ON DELITS 
BEGIN
INSERT INTO HISTORIQUE(table_m,type_m) VALUES ('delits','D');
  NULL;
END;
/
ALTER TRIGGER "WALID"."TRIGGER_DELITS_DELETE" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRIGGER_DELITS_UPDATE
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "WALID"."TRIGGER_DELITS_UPDATE" 
AFTER UPDATE ON DELITS 
BEGIN
INSERT INTO HISTORIQUE(table_m,type_m) VALUES ('delits','U');
  NULL;
END;
/
ALTER TRIGGER "WALID"."TRIGGER_DELITS_UPDATE" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRIGGER_DEMANDES_A
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "WALID"."TRIGGER_DEMANDES_A" 
AFTER INSERT ON DEMANDES_ADMINISTRATIVES 
BEGIN
INSERT INTO HISTORIQUE(table_m,type_m) VALUES ('demandes admin','A');
  NULL;
END;
/
ALTER TRIGGER "WALID"."TRIGGER_DEMANDES_A" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRIGGER_DETENTIONS_AJOUT
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "WALID"."TRIGGER_DETENTIONS_AJOUT" 
AFTER INSERT ON DETENTIONS 
BEGIN
INSERT INTO HISTORIQUE(table_m,type_m) VALUES ('detentions','A');
  NULL;
END;
/
ALTER TRIGGER "WALID"."TRIGGER_DETENTIONS_AJOUT" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRIGGER_DETENTIONS_DELETE
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "WALID"."TRIGGER_DETENTIONS_DELETE" 
AFTER DELETE ON DETENTIONS 
BEGIN
INSERT INTO HISTORIQUE(table_m,type_m) VALUES ('detentions','D');
  NULL;
END;
/
ALTER TRIGGER "WALID"."TRIGGER_DETENTIONS_DELETE" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRIGGER_DETENTIONS_UPDATE
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "WALID"."TRIGGER_DETENTIONS_UPDATE" 
AFTER UPDATE ON DETENTIONS 
BEGIN
INSERT INTO HISTORIQUE(table_m,type_m) VALUES ('detentions','U');
  NULL;
END;
/
ALTER TRIGGER "WALID"."TRIGGER_DETENTIONS_UPDATE" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRIGGER_D_A_DELETE
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "WALID"."TRIGGER_D_A_DELETE" 
AFTER DELETE ON DEMANDES_ADMINISTRATIVES 
BEGIN
INSERT INTO HISTORIQUE(table_m,type_m) VALUES ('demandes admin','D');
  NULL;
END;
/
ALTER TRIGGER "WALID"."TRIGGER_D_A_DELETE" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRIGGER_D_A_UPDATE
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "WALID"."TRIGGER_D_A_UPDATE" 
AFTER UPDATE ON DEMANDES_ADMINISTRATIVES 
BEGIN
INSERT INTO HISTORIQUE(table_m,type_m) VALUES ('demandes admin','U');
  NULL;
END;
/
ALTER TRIGGER "WALID"."TRIGGER_D_A_UPDATE" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRIGGER_D_R_DELETE
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "WALID"."TRIGGER_D_R_DELETE" 
AFTER DELETE ON DEMANDE_REPARATION 
BEGIN
INSERT INTO HISTORIQUE(table_m,type_m) VALUES ('demandes rep','D');
  NULL;
END;
/
ALTER TRIGGER "WALID"."TRIGGER_D_R_DELETE" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRIGGER_D_R_UPDATE
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "WALID"."TRIGGER_D_R_UPDATE" 
AFTER UPDATE ON DEMANDE_REPARATION 
BEGIN
INSERT INTO HISTORIQUE(table_m,type_m) VALUES ('demandes rep','U');
  NULL;
END;
/
ALTER TRIGGER "WALID"."TRIGGER_D_R_UPDATE" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRIGGER_EQUIPEMENTS_AJOUT
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "WALID"."TRIGGER_EQUIPEMENTS_AJOUT" 
AFTER INSERT ON EQUIPEMENTS 
BEGIN
INSERT INTO HISTORIQUE(table_m,type_m) VALUES ('equipements','A');
  NULL;
END;
/
ALTER TRIGGER "WALID"."TRIGGER_EQUIPEMENTS_AJOUT" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRIGGER_EQUIPEMENTS_DELETE
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "WALID"."TRIGGER_EQUIPEMENTS_DELETE" 
AFTER DELETE ON EQUIPEMENTS 
BEGIN
INSERT INTO HISTORIQUE(table_m,type_m) VALUES ('equipements','D');
  NULL;
END;
/
ALTER TRIGGER "WALID"."TRIGGER_EQUIPEMENTS_DELETE" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRIGGER_MISSIONS_AJOUT
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "WALID"."TRIGGER_MISSIONS_AJOUT" 
AFTER INSERT ON MISSIONS 
BEGIN
INSERT INTO HISTORIQUE(table_m,type_m) VALUES ('missions','A');
  NULL;
END;
/
ALTER TRIGGER "WALID"."TRIGGER_MISSIONS_AJOUT" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRIGGER_MISSIONS_DELETE
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "WALID"."TRIGGER_MISSIONS_DELETE" 
AFTER DELETE ON MISSIONS 
BEGIN
INSERT INTO HISTORIQUE(table_m,type_m) VALUES ('missions','D');
  NULL;
END;
/
ALTER TRIGGER "WALID"."TRIGGER_MISSIONS_DELETE" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRIGGER_MISSIONS_UPDATE
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "WALID"."TRIGGER_MISSIONS_UPDATE" 
AFTER UPDATE ON MISSIONS 
BEGIN
INSERT INTO HISTORIQUE(table_m,type_m) VALUES ('missions','U');
  NULL;
END;
/
ALTER TRIGGER "WALID"."TRIGGER_MISSIONS_UPDATE" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRIGGER_POLICIERS_AJOUT
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "WALID"."TRIGGER_POLICIERS_AJOUT" 
AFTER INSERT ON POLICIER 
BEGIN
INSERT INTO HISTORIQUE(table_m,type_m) VALUES ('POLICIER','A');
  NULL;
END;
/
ALTER TRIGGER "WALID"."TRIGGER_POLICIERS_AJOUT" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRIGGER_POLICIER_DELETE
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "WALID"."TRIGGER_POLICIER_DELETE" 
AFTER DELETE ON POLICIER 
BEGIN
INSERT INTO HISTORIQUE(table_m,type_m) VALUES ('policiers','D');
  NULL;
END;
/
ALTER TRIGGER "WALID"."TRIGGER_POLICIER_DELETE" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRIGGER_POLICIER_UPDATE
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "WALID"."TRIGGER_POLICIER_UPDATE" 
AFTER UPDATE ON POLICIER 
BEGIN
INSERT INTO HISTORIQUE(table_m,type_m) VALUES ('policiers','U');
  NULL;
END;
/
ALTER TRIGGER "WALID"."TRIGGER_POLICIER_UPDATE" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRIGGER_VEHICULES_AJOUT
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "WALID"."TRIGGER_VEHICULES_AJOUT" 
AFTER INSERT ON VEHICULES 
BEGIN
    INSERT INTO HISTORIQUE(table_m,type_m) VALUES ('vehicules','A');
    NULL;
END;
/
ALTER TRIGGER "WALID"."TRIGGER_VEHICULES_AJOUT" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRIGGER_VEHICULES_DELETE
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "WALID"."TRIGGER_VEHICULES_DELETE" 
AFTER DELETE ON VEHICULES 
BEGIN
INSERT INTO HISTORIQUE(table_m,type_m) VALUES ('vehicules','D');
  NULL;
END;
/
ALTER TRIGGER "WALID"."TRIGGER_VEHICULES_DELETE" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRIGGER_VEHICULES_UPDATE
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "WALID"."TRIGGER_VEHICULES_UPDATE" 
AFTER UPDATE ON VEHICULES 
BEGIN
INSERT INTO HISTORIQUE(table_m,type_m) VALUES ('vehicules','U');
  NULL;
END;
/
ALTER TRIGGER "WALID"."TRIGGER_VEHICULES_UPDATE" ENABLE;
--------------------------------------------------------
--  Constraints for Table HISTORIQUE
--------------------------------------------------------

  ALTER TABLE "WALID"."HISTORIQUE" ADD CONSTRAINT "HISTORIQUE_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "WALID"."HISTORIQUE" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CRIMINELS
--------------------------------------------------------

  ALTER TABLE "WALID"."CRIMINELS" MODIFY ("IDC" NOT NULL ENABLE);
  ALTER TABLE "WALID"."CRIMINELS" ADD CONSTRAINT "CRIMINELS_PK" PRIMARY KEY ("IDC")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table DELITS
--------------------------------------------------------

  ALTER TABLE "WALID"."DELITS" MODIFY ("ID_DELIT" NOT NULL ENABLE);
  ALTER TABLE "WALID"."DELITS" ADD CONSTRAINT "DELITS_PK" PRIMARY KEY ("ID_DELIT")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table DETENTIONS
--------------------------------------------------------

  ALTER TABLE "WALID"."DETENTIONS" MODIFY ("IDDET" NOT NULL ENABLE);
  ALTER TABLE "WALID"."DETENTIONS" ADD CONSTRAINT "DETENTIONS_PK" PRIMARY KEY ("IDDET")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table CITOYENS
--------------------------------------------------------

  ALTER TABLE "WALID"."CITOYENS" MODIFY ("CIN" NOT NULL ENABLE);
  ALTER TABLE "WALID"."CITOYENS" ADD CONSTRAINT "CITOYENS_PK" PRIMARY KEY ("CIN")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table EQUIPEMENTS
--------------------------------------------------------

  ALTER TABLE "WALID"."EQUIPEMENTS" MODIFY ("IDEQP" NOT NULL ENABLE);
  ALTER TABLE "WALID"."EQUIPEMENTS" ADD CONSTRAINT "EQUIPEMENTS_PK" PRIMARY KEY ("IDEQP")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table DEMANDE_REPARATION
--------------------------------------------------------

  ALTER TABLE "WALID"."DEMANDE_REPARATION" MODIFY ("ID_DEMANDE" NOT NULL ENABLE);
  ALTER TABLE "WALID"."DEMANDE_REPARATION" ADD CONSTRAINT "DEMANDE_REPARATION_PK" PRIMARY KEY ("ID_DEMANDE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table CELLULES
--------------------------------------------------------

  ALTER TABLE "WALID"."CELLULES" MODIFY ("IDCEL" NOT NULL ENABLE);
  ALTER TABLE "WALID"."CELLULES" ADD CONSTRAINT "CELLULES_PK" PRIMARY KEY ("IDCEL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table USER_POLICE
--------------------------------------------------------

  ALTER TABLE "WALID"."USER_POLICE" ADD CONSTRAINT "USER_POLICE_PK" PRIMARY KEY ("ID", "USERNAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "WALID"."USER_POLICE" MODIFY ("USERNAME" NOT NULL ENABLE);
  ALTER TABLE "WALID"."USER_POLICE" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table DEMANDES_ADMINISTRATIVES
--------------------------------------------------------

  ALTER TABLE "WALID"."DEMANDES_ADMINISTRATIVES" MODIFY ("IDDEM" NOT NULL ENABLE);
  ALTER TABLE "WALID"."DEMANDES_ADMINISTRATIVES" ADD CONSTRAINT "DEMANDES_ADMINISTRATIVES_PK" PRIMARY KEY ("IDDEM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table VEHICULES
--------------------------------------------------------

  ALTER TABLE "WALID"."VEHICULES" MODIFY ("MATRICULE" NOT NULL ENABLE);
  ALTER TABLE "WALID"."VEHICULES" ADD CONSTRAINT "VEHICULES_PK" PRIMARY KEY ("MATRICULE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table MISSIONS
--------------------------------------------------------

  ALTER TABLE "WALID"."MISSIONS" MODIFY ("IDM" NOT NULL ENABLE);
  ALTER TABLE "WALID"."MISSIONS" ADD CONSTRAINT "MISSIONS_PK" PRIMARY KEY ("IDM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table POLICIER
--------------------------------------------------------

  ALTER TABLE "WALID"."POLICIER" MODIFY ("IDP" NOT NULL ENABLE);
  ALTER TABLE "WALID"."POLICIER" ADD CONSTRAINT "POLICIER_PK" PRIMARY KEY ("IDP")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CRIMINELS
--------------------------------------------------------

  ALTER TABLE "WALID"."CRIMINELS" ADD CONSTRAINT "CRIMINELS_FK1" FOREIGN KEY ("ID_DELIT")
	  REFERENCES "WALID"."DELITS" ("ID_DELIT") ON DELETE CASCADE ENABLE;
  ALTER TABLE "WALID"."CRIMINELS" ADD CONSTRAINT "CRIMINELS_FK2" FOREIGN KEY ("IDDET")
	  REFERENCES "WALID"."DETENTIONS" ("IDDET") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table DEMANDES_ADMINISTRATIVES
--------------------------------------------------------

  ALTER TABLE "WALID"."DEMANDES_ADMINISTRATIVES" ADD CONSTRAINT "DEMANDES_ADMINISTRATIVES_FK1" FOREIGN KEY ("CIN")
	  REFERENCES "WALID"."CITOYENS" ("CIN") ON DELETE CASCADE ENABLE;
  ALTER TABLE "WALID"."DEMANDES_ADMINISTRATIVES" ADD CONSTRAINT "DEMANDES_ADMINISTRATIVES_FK2" FOREIGN KEY ("IDP")
	  REFERENCES "WALID"."POLICIER" ("IDP") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table DEMANDE_REPARATION
--------------------------------------------------------

  ALTER TABLE "WALID"."DEMANDE_REPARATION" ADD CONSTRAINT "DEMANDE_REPARATION_FK1" FOREIGN KEY ("MATRICULE")
	  REFERENCES "WALID"."VEHICULES" ("MATRICULE") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table DETENTIONS
--------------------------------------------------------

  ALTER TABLE "WALID"."DETENTIONS" ADD CONSTRAINT "DETENTIONS_FK1" FOREIGN KEY ("IDP")
	  REFERENCES "WALID"."POLICIER" ("IDP") ON DELETE CASCADE ENABLE;
  ALTER TABLE "WALID"."DETENTIONS" ADD CONSTRAINT "DETENTIONS_FK2" FOREIGN KEY ("IDCEL")
	  REFERENCES "WALID"."CELLULES" ("IDCEL") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table EQUIPEMENTS
--------------------------------------------------------

  ALTER TABLE "WALID"."EQUIPEMENTS" ADD CONSTRAINT "EQUIPEMENTS_FK1" FOREIGN KEY ("MATRICULE")
	  REFERENCES "WALID"."VEHICULES" ("MATRICULE") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table MISSIONS
--------------------------------------------------------

  ALTER TABLE "WALID"."MISSIONS" ADD CONSTRAINT "MISSIONS_FK1" FOREIGN KEY ("IDP")
	  REFERENCES "WALID"."POLICIER" ("IDP") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table POLICIER
--------------------------------------------------------

  ALTER TABLE "WALID"."POLICIER" ADD CONSTRAINT "POLICIER_FK1" FOREIGN KEY ("IDP_CHEF")
	  REFERENCES "WALID"."POLICIER" ("IDP") ON DELETE CASCADE DISABLE;
--------------------------------------------------------
--  Ref Constraints for Table VEHICULES
--------------------------------------------------------

  ALTER TABLE "WALID"."VEHICULES" ADD CONSTRAINT "VEHICULES_FK1" FOREIGN KEY ("IDP")
	  REFERENCES "WALID"."POLICIER" ("IDP") ON DELETE CASCADE ENABLE;
