--------------------------------------------------------
--  File created - Wednesday-March-24-2021   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table CELLULES
--------------------------------------------------------

  CREATE TABLE "YASSIN"."CELLULES" 
   (	"IDCEL" NUMBER, 
	"NOMBRE_LIT" NUMBER, 
	"NOMBRE_DET" NUMBER, 
	"NOMBRE_DET_MAX" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table CITOYENS
--------------------------------------------------------

  CREATE TABLE "YASSIN"."CITOYENS" 
   (	"CIN" NUMBER, 
	"NOM" VARCHAR2(20 BYTE), 
	"PRENOM" VARCHAR2(20 BYTE), 
	"ADRESSE" VARCHAR2(20 BYTE), 
	"PHOTO" VARCHAR2(200 BYTE), 
	"DATE_NAISSANCE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table CRIMINELS
--------------------------------------------------------

  CREATE TABLE "YASSIN"."CRIMINELS" 
   (	"IDC" NUMBER, 
	"NOM" VARCHAR2(20 BYTE), 
	"PRENOM" VARCHAR2(20 BYTE), 
	"ID_DELIT" NUMBER, 
	"IDDET" NUMBER, 
	"AGE" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table DELITS
--------------------------------------------------------

  CREATE TABLE "YASSIN"."DELITS" 
   (	"ID_DELIT" NUMBER, 
	"DATE_DELIT" DATE, 
	"TYPE" VARCHAR2(20 BYTE), 
	"DESCRIPTION" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table DEMANDES_ADMINISTRATIVES
--------------------------------------------------------

  CREATE TABLE "YASSIN"."DEMANDES_ADMINISTRATIVES" 
   (	"IDDEM" NUMBER, 
	"NOM" VARCHAR2(20 BYTE), 
	"TYPE" VARCHAR2(20 BYTE), 
	"IDP" NUMBER, 
	"CIN" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table DEMANDE_REPARATION
--------------------------------------------------------

  CREATE TABLE "YASSIN"."DEMANDE_REPARATION" 
   (	"MATRICULE" NUMBER, 
	"ID_DEMANDE" NUMBER, 
	"TYPE" VARCHAR2(20 BYTE), 
	"DESCRIPTION" VARCHAR2(2000 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table DETENTIONS
--------------------------------------------------------

  CREATE TABLE "YASSIN"."DETENTIONS" 
   (	"IDDET" NUMBER, 
	"DATE_ENTREE" DATE, 
	"DATE_SORTIE" DATE, 
	"RAISON" VARCHAR2(2000 BYTE), 
	"IDCEL" NUMBER, 
	"IDP" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table EQUIPEMENTS
--------------------------------------------------------

  CREATE TABLE "YASSIN"."EQUIPEMENTS" 
   (	"IDEQP" NUMBER, 
	"MATRICULE" NUMBER, 
	"TYPE" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table MISSIONS
--------------------------------------------------------

  CREATE TABLE "YASSIN"."MISSIONS" 
   (	"IDM" NUMBER, 
	"NOM" VARCHAR2(20 BYTE), 
	"TYPE" VARCHAR2(20 BYTE), 
	"DATE_MISSION" DATE, 
	"IDP" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table POLICIER
--------------------------------------------------------

  CREATE TABLE "YASSIN"."POLICIER" 
   (	"IDP" NUMBER, 
	"NOM" VARCHAR2(20 BYTE), 
	"PRENOM" VARCHAR2(20 BYTE), 
	"GRADE" VARCHAR2(20 BYTE), 
	"IDP_CHEF" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table VEHICULES
--------------------------------------------------------

  CREATE TABLE "YASSIN"."VEHICULES" 
   (	"NOM_MARQUE" VARCHAR2(20 BYTE), 
	"MATRICULE" NUMBER, 
	"DATE_ACHAT" DATE, 
	"IDP" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into YASSIN.CELLULES
SET DEFINE OFF;
REM INSERTING into YASSIN.CITOYENS
SET DEFINE OFF;
REM INSERTING into YASSIN.CRIMINELS
SET DEFINE OFF;
REM INSERTING into YASSIN.DELITS
SET DEFINE OFF;
REM INSERTING into YASSIN.DEMANDES_ADMINISTRATIVES
SET DEFINE OFF;
REM INSERTING into YASSIN.DEMANDE_REPARATION
SET DEFINE OFF;
REM INSERTING into YASSIN.DETENTIONS
SET DEFINE OFF;
REM INSERTING into YASSIN.EQUIPEMENTS
SET DEFINE OFF;
REM INSERTING into YASSIN.MISSIONS
SET DEFINE OFF;
REM INSERTING into YASSIN.POLICIER
SET DEFINE OFF;
REM INSERTING into YASSIN.VEHICULES
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index CRIMINELS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "YASSIN"."CRIMINELS_PK" ON "YASSIN"."CRIMINELS" ("IDC") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index POLICIER_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "YASSIN"."POLICIER_PK" ON "YASSIN"."POLICIER" ("IDP") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index VEHICULES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "YASSIN"."VEHICULES_PK" ON "YASSIN"."VEHICULES" ("MATRICULE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index DELITS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "YASSIN"."DELITS_PK" ON "YASSIN"."DELITS" ("ID_DELIT") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index EQUIPEMENTS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "YASSIN"."EQUIPEMENTS_PK" ON "YASSIN"."EQUIPEMENTS" ("IDEQP") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index DEMANDE_REPARATION_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "YASSIN"."DEMANDE_REPARATION_PK" ON "YASSIN"."DEMANDE_REPARATION" ("ID_DEMANDE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index DEMANDES_ADMINISTRATIVES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "YASSIN"."DEMANDES_ADMINISTRATIVES_PK" ON "YASSIN"."DEMANDES_ADMINISTRATIVES" ("IDDEM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index MISSIONS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "YASSIN"."MISSIONS_PK" ON "YASSIN"."MISSIONS" ("IDM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index DETENTIONS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "YASSIN"."DETENTIONS_PK" ON "YASSIN"."DETENTIONS" ("IDDET") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index CITOYENS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "YASSIN"."CITOYENS_PK" ON "YASSIN"."CITOYENS" ("CIN") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index CELLULES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "YASSIN"."CELLULES_PK" ON "YASSIN"."CELLULES" ("IDCEL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table POLICIER
--------------------------------------------------------

  ALTER TABLE "YASSIN"."POLICIER" ADD CONSTRAINT "POLICIER_PK" PRIMARY KEY ("IDP")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "YASSIN"."POLICIER" MODIFY ("IDP" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table DELITS
--------------------------------------------------------

  ALTER TABLE "YASSIN"."DELITS" ADD CONSTRAINT "DELITS_PK" PRIMARY KEY ("ID_DELIT")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "YASSIN"."DELITS" MODIFY ("ID_DELIT" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CITOYENS
--------------------------------------------------------

  ALTER TABLE "YASSIN"."CITOYENS" ADD CONSTRAINT "CITOYENS_PK" PRIMARY KEY ("CIN")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "YASSIN"."CITOYENS" MODIFY ("CIN" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CRIMINELS
--------------------------------------------------------

  ALTER TABLE "YASSIN"."CRIMINELS" ADD CONSTRAINT "CRIMINELS_PK" PRIMARY KEY ("IDC")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "YASSIN"."CRIMINELS" MODIFY ("IDC" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table EQUIPEMENTS
--------------------------------------------------------

  ALTER TABLE "YASSIN"."EQUIPEMENTS" ADD CONSTRAINT "EQUIPEMENTS_PK" PRIMARY KEY ("IDEQP")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "YASSIN"."EQUIPEMENTS" MODIFY ("IDEQP" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table MISSIONS
--------------------------------------------------------

  ALTER TABLE "YASSIN"."MISSIONS" ADD CONSTRAINT "MISSIONS_PK" PRIMARY KEY ("IDM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "YASSIN"."MISSIONS" MODIFY ("IDM" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table DEMANDES_ADMINISTRATIVES
--------------------------------------------------------

  ALTER TABLE "YASSIN"."DEMANDES_ADMINISTRATIVES" ADD CONSTRAINT "DEMANDES_ADMINISTRATIVES_PK" PRIMARY KEY ("IDDEM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "YASSIN"."DEMANDES_ADMINISTRATIVES" MODIFY ("IDDEM" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CELLULES
--------------------------------------------------------

  ALTER TABLE "YASSIN"."CELLULES" ADD CONSTRAINT "CELLULES_PK" PRIMARY KEY ("IDCEL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "YASSIN"."CELLULES" MODIFY ("IDCEL" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table VEHICULES
--------------------------------------------------------

  ALTER TABLE "YASSIN"."VEHICULES" ADD CONSTRAINT "VEHICULES_PK" PRIMARY KEY ("MATRICULE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "YASSIN"."VEHICULES" MODIFY ("MATRICULE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table DETENTIONS
--------------------------------------------------------

  ALTER TABLE "YASSIN"."DETENTIONS" ADD CONSTRAINT "DETENTIONS_PK" PRIMARY KEY ("IDDET")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "YASSIN"."DETENTIONS" MODIFY ("IDDET" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table DEMANDE_REPARATION
--------------------------------------------------------

  ALTER TABLE "YASSIN"."DEMANDE_REPARATION" ADD CONSTRAINT "DEMANDE_REPARATION_PK" PRIMARY KEY ("ID_DEMANDE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "YASSIN"."DEMANDE_REPARATION" MODIFY ("ID_DEMANDE" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table CRIMINELS
--------------------------------------------------------

  ALTER TABLE "YASSIN"."CRIMINELS" ADD CONSTRAINT "CRIMINELS_FK1" FOREIGN KEY ("ID_DELIT")
	  REFERENCES "YASSIN"."DELITS" ("ID_DELIT") ON DELETE CASCADE ENABLE;
  ALTER TABLE "YASSIN"."CRIMINELS" ADD CONSTRAINT "CRIMINELS_FK2" FOREIGN KEY ("IDDET")
	  REFERENCES "YASSIN"."DETENTIONS" ("IDDET") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table DEMANDES_ADMINISTRATIVES
--------------------------------------------------------

  ALTER TABLE "YASSIN"."DEMANDES_ADMINISTRATIVES" ADD CONSTRAINT "DEMANDES_ADMINISTRATIVES_FK1" FOREIGN KEY ("CIN")
	  REFERENCES "YASSIN"."CITOYENS" ("CIN") ON DELETE CASCADE ENABLE;
  ALTER TABLE "YASSIN"."DEMANDES_ADMINISTRATIVES" ADD CONSTRAINT "DEMANDES_ADMINISTRATIVES_FK2" FOREIGN KEY ("IDP")
	  REFERENCES "YASSIN"."POLICIER" ("IDP") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table DEMANDE_REPARATION
--------------------------------------------------------

  ALTER TABLE "YASSIN"."DEMANDE_REPARATION" ADD CONSTRAINT "DEMANDE_REPARATION_FK1" FOREIGN KEY ("MATRICULE")
	  REFERENCES "YASSIN"."VEHICULES" ("MATRICULE") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table DETENTIONS
--------------------------------------------------------

  ALTER TABLE "YASSIN"."DETENTIONS" ADD CONSTRAINT "DETENTIONS_FK1" FOREIGN KEY ("IDP")
	  REFERENCES "YASSIN"."POLICIER" ("IDP") ON DELETE CASCADE ENABLE;
  ALTER TABLE "YASSIN"."DETENTIONS" ADD CONSTRAINT "DETENTIONS_FK2" FOREIGN KEY ("IDCEL")
	  REFERENCES "YASSIN"."CELLULES" ("IDCEL") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table EQUIPEMENTS
--------------------------------------------------------

  ALTER TABLE "YASSIN"."EQUIPEMENTS" ADD CONSTRAINT "EQUIPEMENTS_FK1" FOREIGN KEY ("MATRICULE")
	  REFERENCES "YASSIN"."VEHICULES" ("MATRICULE") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table MISSIONS
--------------------------------------------------------

  ALTER TABLE "YASSIN"."MISSIONS" ADD CONSTRAINT "MISSIONS_FK1" FOREIGN KEY ("IDP")
	  REFERENCES "YASSIN"."POLICIER" ("IDP") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table POLICIER
--------------------------------------------------------

  ALTER TABLE "YASSIN"."POLICIER" ADD CONSTRAINT "POLICIER_FK1" FOREIGN KEY ("IDP_CHEF")
	  REFERENCES "YASSIN"."POLICIER" ("IDP") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table VEHICULES
--------------------------------------------------------

  ALTER TABLE "YASSIN"."VEHICULES" ADD CONSTRAINT "VEHICULES_FK1" FOREIGN KEY ("IDP")
	  REFERENCES "YASSIN"."POLICIER" ("IDP") ON DELETE CASCADE ENABLE;
