--------------------------------------------------------
--  File created - Wednesday-March-24-2021   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table CELLULES
--------------------------------------------------------

  CREATE TABLE "CELLULES" 
   (	"IDCEL" NUMBER, 
	"NOMBRE_LIT" NUMBER, 
	"NOMBRE_DET" NUMBER, 
	"NOMBRE_DET_MAX" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table CITOYENS
--------------------------------------------------------

  CREATE TABLE "CITOYENS" 
   (	"CIN" NUMBER, 
	"NOM" VARCHAR2(20 BYTE), 
	"PRENOM" VARCHAR2(20 BYTE), 
	"ADRESSE" VARCHAR2(20 BYTE), 
	"PHOTO" VARCHAR2(200 BYTE), 
	"DATE_NAISSANCE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table CRIMINELS
--------------------------------------------------------

  CREATE TABLE "CRIMINELS" 
   (	"IDC" NUMBER, 
	"NOM" VARCHAR2(20 BYTE), 
	"PRENOM" VARCHAR2(20 BYTE), 
	"ID_DELIT" NUMBER, 
	"IDDET" NUMBER, 
	"AGE" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table DELITS
--------------------------------------------------------

  CREATE TABLE "DELITS" 
   (	"ID_DELIT" NUMBER, 
	"DATE_DELIT" DATE, 
	"TYPE" VARCHAR2(20 BYTE), 
	"DESCRIPTION" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table DEMANDES_ADMINISTRATIVES
--------------------------------------------------------

  CREATE TABLE "DEMANDES_ADMINISTRATIVES" 
   (	"IDDEM" NUMBER, 
	"NOM" VARCHAR2(20 BYTE), 
	"TYPE" VARCHAR2(20 BYTE), 
	"IDP" NUMBER, 
	"CIN" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table DEMANDE_REPARATION
--------------------------------------------------------

  CREATE TABLE "DEMANDE_REPARATION" 
   (	"MATRICULE" NUMBER, 
	"ID_DEMANDE" NUMBER, 
	"TYPE" VARCHAR2(20 BYTE), 
	"DESCRIPTION" VARCHAR2(2000 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table DETENTIONS
--------------------------------------------------------

  CREATE TABLE "DETENTIONS" 
   (	"IDDET" NUMBER, 
	"DATE_ENTREE" DATE, 
	"DATE_SORTIE" DATE, 
	"RAISON" VARCHAR2(2000 BYTE), 
	"IDCEL" NUMBER, 
	"IDP" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table EQUIPEMENTS
--------------------------------------------------------

  CREATE TABLE "EQUIPEMENTS" 
   (	"IDEQP" NUMBER, 
	"MATRICULE" NUMBER, 
	"TYPE" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table MISSIONS
--------------------------------------------------------

  CREATE TABLE "MISSIONS" 
   (	"IDM" NUMBER, 
	"NOM" VARCHAR2(20 BYTE), 
	"TYPE" VARCHAR2(20 BYTE), 
	"DATE_MISSION" DATE, 
	"IDP" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table POLICIER
--------------------------------------------------------

  CREATE TABLE "POLICIER" 
   (	"IDP" NUMBER, 
	"NOM" VARCHAR2(20 BYTE), 
	"PRENOM" VARCHAR2(20 BYTE), 
	"GRADE" VARCHAR2(20 BYTE), 
	"IDP_CHEF" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table VEHICULES
--------------------------------------------------------

  CREATE TABLE "VEHICULES" 
   (	"NOM_MARQUE" VARCHAR2(20 BYTE), 
	"MATRICULE" NUMBER, 
	"DATE_ACHAT" DATE, 
	"IDP" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into walid.CELLULES
SET DEFINE OFF;
REM INSERTING into walid.CITOYENS
SET DEFINE OFF;
REM INSERTING into walid.CRIMINELS
SET DEFINE OFF;
REM INSERTING into walid.DELITS
SET DEFINE OFF;
REM INSERTING into walid.DEMANDES_ADMINISTRATIVES
SET DEFINE OFF;
REM INSERTING into walid.DEMANDE_REPARATION
SET DEFINE OFF;
REM INSERTING into walid.DETENTIONS
SET DEFINE OFF;
REM INSERTING into walid.EQUIPEMENTS
SET DEFINE OFF;
REM INSERTING into walid.MISSIONS
SET DEFINE OFF;
REM INSERTING into walid.POLICIER
SET DEFINE OFF;
REM INSERTING into walid.VEHICULES
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index CRIMINELS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "CRIMINELS_PK" ON "CRIMINELS" ("IDC") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index POLICIER_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "POLICIER_PK" ON "POLICIER" ("IDP") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index VEHICULES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "VEHICULES_PK" ON "VEHICULES" ("MATRICULE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index DELITS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "DELITS_PK" ON "DELITS" ("ID_DELIT") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index EQUIPEMENTS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "EQUIPEMENTS_PK" ON "EQUIPEMENTS" ("IDEQP") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index DEMANDE_REPARATION_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "DEMANDE_REPARATION_PK" ON "DEMANDE_REPARATION" ("ID_DEMANDE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index DEMANDES_ADMINISTRATIVES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "DEMANDES_ADMINISTRATIVES_PK" ON "DEMANDES_ADMINISTRATIVES" ("IDDEM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index MISSIONS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "MISSIONS_PK" ON "MISSIONS" ("IDM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index DETENTIONS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "DETENTIONS_PK" ON "DETENTIONS" ("IDDET") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index CITOYENS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "CITOYENS_PK" ON "CITOYENS" ("CIN") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index CELLULES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "CELLULES_PK" ON "CELLULES" ("IDCEL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table POLICIER
--------------------------------------------------------

  ALTER TABLE "POLICIER" ADD CONSTRAINT "POLICIER_PK" PRIMARY KEY ("IDP")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "POLICIER" MODIFY ("IDP" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table DELITS
--------------------------------------------------------

  ALTER TABLE "DELITS" ADD CONSTRAINT "DELITS_PK" PRIMARY KEY ("ID_DELIT")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "DELITS" MODIFY ("ID_DELIT" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CITOYENS
--------------------------------------------------------

  ALTER TABLE "CITOYENS" ADD CONSTRAINT "CITOYENS_PK" PRIMARY KEY ("CIN")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "CITOYENS" MODIFY ("CIN" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CRIMINELS
--------------------------------------------------------

  ALTER TABLE "CRIMINELS" ADD CONSTRAINT "CRIMINELS_PK" PRIMARY KEY ("IDC")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "CRIMINELS" MODIFY ("IDC" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table EQUIPEMENTS
--------------------------------------------------------

  ALTER TABLE "EQUIPEMENTS" ADD CONSTRAINT "EQUIPEMENTS_PK" PRIMARY KEY ("IDEQP")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "EQUIPEMENTS" MODIFY ("IDEQP" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table MISSIONS
--------------------------------------------------------

  ALTER TABLE "MISSIONS" ADD CONSTRAINT "MISSIONS_PK" PRIMARY KEY ("IDM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "MISSIONS" MODIFY ("IDM" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table DEMANDES_ADMINISTRATIVES
--------------------------------------------------------

  ALTER TABLE "DEMANDES_ADMINISTRATIVES" ADD CONSTRAINT "DEMANDES_ADMINISTRATIVES_PK" PRIMARY KEY ("IDDEM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "DEMANDES_ADMINISTRATIVES" MODIFY ("IDDEM" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CELLULES
--------------------------------------------------------

  ALTER TABLE "CELLULES" ADD CONSTRAINT "CELLULES_PK" PRIMARY KEY ("IDCEL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "CELLULES" MODIFY ("IDCEL" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table VEHICULES
--------------------------------------------------------

  ALTER TABLE "VEHICULES" ADD CONSTRAINT "VEHICULES_PK" PRIMARY KEY ("MATRICULE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "VEHICULES" MODIFY ("MATRICULE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table DETENTIONS
--------------------------------------------------------

  ALTER TABLE "DETENTIONS" ADD CONSTRAINT "DETENTIONS_PK" PRIMARY KEY ("IDDET")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "DETENTIONS" MODIFY ("IDDET" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table DEMANDE_REPARATION
--------------------------------------------------------

  ALTER TABLE "DEMANDE_REPARATION" ADD CONSTRAINT "DEMANDE_REPARATION_PK" PRIMARY KEY ("ID_DEMANDE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "DEMANDE_REPARATION" MODIFY ("ID_DEMANDE" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table CRIMINELS
--------------------------------------------------------

  ALTER TABLE "CRIMINELS" ADD CONSTRAINT "CRIMINELS_FK1" FOREIGN KEY ("ID_DELIT")
	  REFERENCES "DELITS" ("ID_DELIT") ON DELETE CASCADE ENABLE;
  ALTER TABLE "CRIMINELS" ADD CONSTRAINT "CRIMINELS_FK2" FOREIGN KEY ("IDDET")
	  REFERENCES "DETENTIONS" ("IDDET") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table DEMANDES_ADMINISTRATIVES
--------------------------------------------------------

  ALTER TABLE "DEMANDES_ADMINISTRATIVES" ADD CONSTRAINT "DEMANDES_ADMINISTRATIVES_FK1" FOREIGN KEY ("CIN")
	  REFERENCES "CITOYENS" ("CIN") ON DELETE CASCADE ENABLE;
  ALTER TABLE "DEMANDES_ADMINISTRATIVES" ADD CONSTRAINT "DEMANDES_ADMINISTRATIVES_FK2" FOREIGN KEY ("IDP")
	  REFERENCES "POLICIER" ("IDP") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table DEMANDE_REPARATION
--------------------------------------------------------

  ALTER TABLE "DEMANDE_REPARATION" ADD CONSTRAINT "DEMANDE_REPARATION_FK1" FOREIGN KEY ("MATRICULE")
	  REFERENCES "VEHICULES" ("MATRICULE") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table DETENTIONS
--------------------------------------------------------

  ALTER TABLE "DETENTIONS" ADD CONSTRAINT "DETENTIONS_FK1" FOREIGN KEY ("IDP")
	  REFERENCES "POLICIER" ("IDP") ON DELETE CASCADE ENABLE;
  ALTER TABLE "DETENTIONS" ADD CONSTRAINT "DETENTIONS_FK2" FOREIGN KEY ("IDCEL")
	  REFERENCES "CELLULES" ("IDCEL") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table EQUIPEMENTS
--------------------------------------------------------

  ALTER TABLE "EQUIPEMENTS" ADD CONSTRAINT "EQUIPEMENTS_FK1" FOREIGN KEY ("MATRICULE")
	  REFERENCES "VEHICULES" ("MATRICULE") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table MISSIONS
--------------------------------------------------------

  ALTER TABLE "MISSIONS" ADD CONSTRAINT "MISSIONS_FK1" FOREIGN KEY ("IDP")
	  REFERENCES "POLICIER" ("IDP") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table POLICIER
--------------------------------------------------------

  ALTER TABLE "POLICIER" ADD CONSTRAINT "POLICIER_FK1" FOREIGN KEY ("IDP_CHEF")
	  REFERENCES "POLICIER" ("IDP") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table VEHICULES
--------------------------------------------------------

  ALTER TABLE "VEHICULES" ADD CONSTRAINT "VEHICULES_FK1" FOREIGN KEY ("IDP")
	  REFERENCES "POLICIER" ("IDP") ON DELETE CASCADE ENABLE;
